---
cognite: # kwargs to pass to the CogniteClient, Environment variable format: ${ENVIRONMENT_VARIABLE}
    host: ${EXTPIPES_CDF_HOST}
    project: ${EXTPIPES_CDF_PROJECT}

    idp-authentication:
        client-id: ${EXTPIPES_IDP_CLIENT_ID}
        secret: ${EXTPIPES_IDP_CLIENT_SECRET}
        scopes:
            - ${EXTPIPES_IDP_SCOPES}
        token_url: ${EXTPIPES_IDP_TOKEN_URL}

logger:
    file:
        path: ./logs/test-deploy.log
        level: INFO
    console:
        level: INFO

extpipe-pattern: '{source}:{short-name}:{rawtable-name}:{suffix}'

# can contain multiple contacts, can be overwritten on pipeline level
default-contacts:
    - name: Support
      email: trygve.carlsen@akersolutions.com
      role: admin
      send-notification: false

rawdbs:
  # list of raw-dbs > containing rawtables > containing pipelines
    - rawdb-name: src:001:sap:db
      dataset-external-id: src:001:sap:ds
      short-name: sap
      rawtables:
          - rawtable-name: assets
            pipelines:
                - source: csv
                  schedule: On trigger
                  contacts:
                      - name: Support
                        email: trygve.carlsen@akersolutions.com
                        role: data engineer
                        send-notification: false
    - rawdb-name: src:002:opcua:db
      short-name: opcua
      dataset-external-id: src:002:opcua:ds
      rawtables:
          - rawtable-name: datapoints
            pipelines:
                - source: ice-cream-api
                  schedule: On trigger
                  contacts:
                      - name: Support
                        email: trygve.carlsen@akersolutions.com
                        role: data engineer
                        send-notification: false
