---
name: deploy-extpipes-cli
# GAAAAAH!!!! HVA FAEN ER DETTE!?
on:
    push:
        branches:
            - main
        paths:
            - config/extpipes/**
            - .github/workflows/deploy-extpipes-cli.yaml

jobs:
    deploy_extpipes:
        name: deploy extpipes-cli
        runs-on: ubuntu-latest
        strategy:
            matrix:
                environment: [test, prod]
                include:
                    - environment: test
                      CDF_CLUSTER: westeurope-1
                      CDF_PROJECT: cdf-bootcamp-09-test
                      IDP_TENANT: 16e3985b-ebe8-4e24-9da4-933e21a9fc81
                    - environment: prod
                      CDF_CLUSTER: westeurope-1
                      CDF_PROJECT: cdf-bootcamp-09-prod
                      IDP_TENANT: 16e3985b-ebe8-4e24-9da4-933e21a9fc81

        environment: ${{ matrix.environment}}
        env:
            CDF_HOST: https://${{ matrix.CDF_CLUSTER }}.cognitedata.com/

        steps:
            - uses: actions/checkout@v3
            - uses: cognitedata/inso-extpipes-cli@main
              env:
                  EXTPIPES_IDP_CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  EXTPIPES_IDP_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                  EXTPIPES_CDF_HOST: ${{ env.CDF_HOST }}
                  EXTPIPES_CDF_PROJECT: ${{ matrix.CDF_PROJECT }}
                  EXTPIPES_IDP_TOKEN_URL: https://login.microsoftonline.com/${{ matrix.IDP_TENANT }}/oauth2/v2.0/token
                  EXTPIPES_IDP_SCOPES: ${{ env.CDF_HOST }}.default

              with:
                  config_file: ./config/extpipes/extpipes-cli-config.yml
